[watch]
ignore = [
    "db.sqlite",
    "db.sqlite-wal",
    "db.sqlite-shm",
    "db.sqlite-journal",  # Fichier journal de SQLite
    "*.log",
    "logs/*",
    "*.tmp",
    "*.swp",
    "*.swx",
    ".DS_Store"
]